version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
   container_name: elasticsearch
   ports:
    - "9200:9200"
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   networks:
    - docker-network

  kibana:
   image: docker.elastic.co/kibana/kibana:7.2.0
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_URL}
    - XPACK_MONITORING_ENABLED=true
   networks:
    - docker-network

  apmserver:
    image: docker.elastic.co/apm/apm-server:7.5.2
    command: --strict.perms=false
    ports:
      - 8200:8200
    environment:
      - apm-server.host=0.0.0.0
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data: